# Generated by Django 4.2.6 on 2023-10-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0006_remove_book_user'),
        ('shopping_page', '0003_cart_user_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ManyToManyField(to='bookfinds.book'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping_page.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Transfer Bank'), (2, 'Gopay'), (3, 'OvO')]),
        ),
    ]
