# Generated by Django 4.2.6 on 2023-10-25 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RegLogInOut', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLT',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userLT',
            new_name='user',
        ),
    ]
