# Generated by Django 4.2.6 on 2023-10-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegLogInOut', '0002_rename_userlt_user_rename_userlt_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
