# Generated by Django 4.2.6 on 2023-10-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
    ]
