# Generated by Django 4.2.6 on 2023-10-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookfinds', '0004_alter_book_isbn'),
        ('bookclub', '0002_remove_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='recommended_books',
            field=models.ManyToManyField(related_name='recommended_in_clubs', to='bookfinds.book'),
        ),
    ]
