# Generated by Django 4.2.6 on 2023-10-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_club_owner_alter_club_recommended_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubble',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookclub.club'),
            preserve_default=False,
        ),
    ]
