# Generated by Django 4.2.6 on 2023-10-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_club_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
    ]
