# Generated by Django 4.2.6 on 2023-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('description', models.TextField()),
                ('published_year', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('ACC', 'Accepted'), ('DEN', 'Denied')], default='REQ', max_length=3)),
            ],
        ),
    ]
