# Generated by Django 4.2.6 on 2023-11-20 09:32

from django.db import migrations
from django.core.management import call_command 

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books_100.json")

class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0002_bookrequest_user'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
