# Generated by Django 4.2.6 on 2023-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0003_rename_categories_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10),
        ),
    ]
