# Generated by Django 4.2.6 on 2023-10-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
