<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
=======
# Generated by Django 4.2.6 on 2023-10-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
>>>>>>> 99c2e2d992d9f7359eb799f914ed60455612f3f6
