# Generated by Django 4.2.6 on 2023-10-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0005_book_user'),
        ('bookfinds', '0005_bookrequest'),
    ]

    operations = [
    ]
