# Generated by Django 4.2.6 on 2023-10-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0005_bookrequest'),
        ('bookfinds', '0006_remove_book_user'),
    ]

    operations = [
    ]
