# Generated by Django 4.2.6 on 2023-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0006_merge_0005_book_user_0005_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('REQ', 'Requested'), ('ACC', 'Accepted'), ('DEN', 'Denied')], default='REQ', max_length=3),
        ),
    ]
