# Generated by Django 4.2.6 on 2023-10-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfinds', '0007_merge_0005_bookrequest_0006_remove_book_user'),
        ('bookfinds', '0007_remove_book_user_bookrequest_status'),
    ]

    operations = [
    ]
